#lang racket
(define (masomenos n1 n2 n3 n4)
  (cond ((and (zero? n1)
       (zero? n2)
       (zero? n3)
       (zero? n4) (quote empate)))
       ((positive? n1 n2 n3 n4) (quote positivo))
       (else 'negativo))
       )
(define (positive? n1 n2 n3 n4)
  (and (> n1 0)
       (> n2 0)
       (> n3 0)
       (> n4 0)))
(define (zero? n1)
  (and (= n1 0)))